version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
